### ISSUE TITLE
events page

### ISSUE THREAD

**Issue by Athanasiamo** [rladies/website#12]
The events page is also powered heavily by Rmd. 
Ignoring the needed changes for getting events through CIs in #11.

To adhere to wanted changes in #9 the page needs following changes:

- [x]  move css to rladies.css in the theme repo (https://github.com/rladies/hugo-initio/blob/master/static/css/rladies.css)

- [x]  switch from Rmd to hugo data templates.

**Comment by Athanasiamo** [comment]
there is some progress on this in [c83d6b47b53d](https://github.com/rladies/website/commit/c83d6b47b53d8d7a38d76afe363dd63f961e16b4).

Ive just been playing around with the html in the content file, just to test things out and see how things work and why.
So far, nothing works and I dont know why :P 

The calendar grid is created, but I cannot populate it.

**Comment by Athanasiamo** [comment]
Also, there are quite some js-libs linked to do this, and maybe it's better to set up footer blocks so that the tui js is onlu loaded for the events page and not for the entire page always. I dont know if that has anything to say for speed if the page anyway does not call the js-scripts?

**Comment by maelle** [comment]
I think that one should not only generate an OAuth token for this use case but also a specific OAuth consumer/app see https://secure.meetup.com/meetup_api/oauth_consumers/ (what is called third-party app in https://github.com/r-hub/blog/pull/142 <- all I know about OAuth!). Otherwise imagine someone uses the meetupr default app and depletes the (undocumented) request limit for a while: in this case the website infrastructure could no longer fetch events.

**Comment by Athanasiamo** [comment]
events page is now fully in hugo data templates.
